version: "3.8"

services:
  db:
    build:
      context: ./llm_rag/db
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: resumes_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: llm_rag/api
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/resumes_db"
    volumes:
      - .:/app

volumes:
  postgres_data: